AWSTemplateFormatVersion: '2010-09-09'
Description: 'Plantilla de CloudFormation para lanzar una instancia EC2'

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04a81a99f5ec58529 # Ubuntu Server 22.04 LTS (HVM), SSD Volume Type
      KeyName: sammycantoral # Aquí debes reemplazar con el nombre exacto de tu llave SSH en AWS
      SecurityGroups:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: MyEC2Instance

  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Permite el acceso SSH y HTTP'
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'  # Permite acceso SSH desde cualquier IP
        - IpProtocol: 'tcp'
          FromPort: '80'
          ToPort: '80'
          CidrIp: '0.0.0.0/0'  # Permite acceso HTTP desde cualquier IP